### ISSUE TITLE
Something meaningless

### ISSUE THREAD

**Issue by Yiliu1412** [YBRua/chat_history_word_cloud#1]
Dear maintainer,

I came across your repository for generating word clouds and I was impressed with its functionality. However, I noticed that the current implementation generates word clouds based on a corpus of text, rather than single user's speech.

I was wondering if it would be possible to add a feature that generates word clouds based on a single user's speech? This would be very useful for analyzing the word usage patterns of an individual user, rather than a collection of users.

Thank you for your hard work and consideration.

Best regards,
Yiliu1412

**Comment by Kevin-ZhangClutchit** [comment]
Hey, I believe if you want it urgently, you can self try to modify the code of `def read(self, path: str) -> List[ChatMessage]:`  to something like

```python
 def read(self, path: str) -> List[ChatMessage]:
        self.cursor = 0
        with open(path, 'r', encoding='utf-8') as f:
            self.lines = f.readlines()

        while self._has_next_line():
            if self._is_message_header(self._get_current_line()):
                tmp=self._process_message()
                if tmp.sender_id == "someones uid":
                    self.msgs.append(tmp)
            self._next_line()

        return self.msgs
```

just to only save messages of certain reader

**Comment by YBRua** [comment]
Hi yiliu,

Thanks for your interest in this project!

Generating word cloud for a designated user is a planned feature. The original plan was to add a filter or something so that only the filtered chat history will be used for word cloud generation. Unfortunately I am too busy to update this project recently, and I'm afraid there won't be an actual update until early May.

For now, @Kevin-ZhangClutchit ‘s solution would suffice as a quick workaround.

**Comment by Yiliu1412** [comment]
That's very nice of you two guys!🤩I'm just recently learning it to make some charts to beautify my course report. This repository does do a lot help.

Thanks😘.
